baseURL: "https://davidsvida.github.io"
title: David
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-C82WSJW7GT

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: David
  description: "David Cepeda's personal website with random stuff that he wants to put out on the internet "
  keywords: [Blog, Portfolio, PaperMod]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "favicon.svg"

  profileMode:
    enabled: false
    title: david
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi \U0001F32E"
    Content: My name is David Cepeda. I love math and science, and I enjoy traveling and experiencing new things.

  socialIcons:
    - name: ycombinator
      url: "https://news.ycombinator.com/user?id=davidsvida"
    - name: youtube
      url: "https://www.youtube.com/@davidsvida679"
    - name: github
      url: "https://github.com/davidsvida"
    - name: other 
      url: "google.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/davidcepeda05/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: search
      name: Search 
      url: /search/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
