baseURL: "https://davidsvida.github.io"
title: David
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false



googleAnalytics: G-C82WSJW7GT

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: david
  description: "David Cepeda's personal website with random stuff that he wants to put out on the internet "
  keywords: [Blog, Portfolio, PaperMod]
  author: David Cepeda
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicons/favicon.ico"


  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: david
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi \U0001F32E"
    Content: My name is David Cepeda. I love math and science, and I enjoy traveling and experiencing new things. 

  socialIcons:
    - name: ycombinator
      url: "https://news.ycombinator.com/user?id=davidsvida"
    - name: youtube
      url: "https://www.youtube.com/@davidsvida679"
    - name: github
      url: "https://github.com/davidsvida"
    - name: other 
      url: "google.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/davidcepeda05/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Archive
      url: archives
      weight: 10
    - identifier: Search 
      name: Search
      url: search
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai